# Generated by Django 4.1.6 on 2023-02-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('S', 'SOLICITADO'), ('EP', 'EN PREPARACION'), ('EC', 'EN CAMINO'), ('E', 'ENTREGADO')], default='S', max_length=2),
        ),
    ]
