# Generated by Django 4.1.6 on 2023-02-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_restaurante_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='url',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='imagen',
            field=models.ImageField(default='', upload_to='platos/'),
        ),
    ]
