# Generated by Django 4.1.6 on 2023-02-16 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0004_remove_restaurante_url_restaurante_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('img', models.ImageField(upload_to='platos/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='endpoints.categoria')),
            ],
        ),
        migrations.RenameModel(
            old_name='Plato',
            new_name='Platos',
        ),
        migrations.RenameField(
            model_name='platos',
            old_name='imagen',
            new_name='img',
        ),
        migrations.DeleteModel(
            name='Restaurante',
        ),
    ]
