# Generated by Django 4.1.6 on 2023-02-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0005_restaurantes_rename_plato_platos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantes',
            name='img',
        ),
        migrations.RemoveField(
            model_name='restaurantes',
            name='precio',
        ),
        migrations.AddField(
            model_name='restaurantes',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platos',
            name='img',
            field=models.URLField(),
        ),
    ]
