# Generated by Django 4.1.6 on 2023-02-21 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0006_remove_restaurantes_img_remove_restaurantes_precio_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Platos',
            new_name='Plato',
        ),
        migrations.RenameModel(
            old_name='Restaurantes',
            new_name='Restaurante',
        ),
    ]
