# Generated by Django 4.1.6 on 2023-02-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0007_rename_platos_plato_rename_restaurantes_restaurante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='nombre',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='restaurante',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='categoria',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='date',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurante',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
