# Generated by Django 4.1.6 on 2023-02-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0009_pedido_pedidoxplato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoxplato',
            name='precio',
        ),
        migrations.AddField(
            model_name='pedido',
            name='detalles',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
