# Generated by Django 4.1.6 on 2023-02-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0010_remove_pedidoxplato_precio_pedido_detalles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(default='', max_length=6),
        ),
    ]
