# Generated by Django 4.1.6 on 2023-02-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0011_pedido_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='precio',
            new_name='total',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(default='ABC123', max_length=6),
        ),
    ]
