# Generated by Django 4.1.6 on 2023-02-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0012_rename_precio_pedido_total_alter_pedido_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
