# Generated by Django 4.1.6 on 2023-02-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0013_alter_pedido_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='referencias',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedidoxplato',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default='', max_digits=6),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='detalles',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pedidoxplato',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
