# Generated by Django 4.1.6 on 2023-02-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0016_alter_pedidoxplato_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoxplato',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
