# Generated by Django 4.1.6 on 2023-02-24 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0017_alter_pedidoxplato_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoxplato',
            name='cantidad',
        ),
    ]
