# Generated by Django 4.1.6 on 2023-02-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0018_remove_pedidoxplato_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='referencias',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='detalles',
            field=models.CharField(default='', max_length=100),
        ),
    ]
