# Generated by Django 4.1.6 on 2023-02-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0019_remove_pedido_referencias_alter_pedido_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='referencias',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedidoxplato',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
